use super::GAME_OVER_PANEL_TOP_DEFAULT_FLOAT;

pub const GAME_OVER_PANEL_TIMER_ANIMATION: f32 = 1.;
pub const GAME_OVER_PANEL_DEFAULT_SPEED_ANIMATION: f32 = 1.;
pub const GAME_OVER_PANEL_SHOW_MUL_SPEED_ANIMATION: f32 = 1.;
pub const GAME_OVER_PANEL_HIDE_MUL_SPEED_ANIMATION: f32 = 5.;
pub static GAME_OVER_PANEL_TOP_END_FLOAT: f32 = GAME_OVER_PANEL_TOP_DEFAULT_FLOAT / 2. - 10.;
pub static GAME_OVER_PANEL_TOP_REVERSE_END_FLOAT: f32 =
    GAME_OVER_PANEL_TOP_DEFAULT_FLOAT - GAME_OVER_PANEL_TOP_END_FLOAT;
