use super::GAME_OVER_PANEL_TOP_DEFAULT_VALUE;

pub const GAME_OVER_PANEL_ANIMATION_TIMER: f32 = 1.;
pub const GAME_OVER_PANEL_ANIMATION_SPEED_DEFAULT: f32 = 1.;
pub const GAME_OVER_PANEL_ANIMATION_SPEED_SHOW_MULTIPLIER: f32 = 1.;
pub const GAME_OVER_PANEL_ANIMATION_SPEED_HIDE_MULTIPLIER: f32 = 5.;
pub static GAME_OVER_PANEL_TOP_END: f32 = GAME_OVER_PANEL_TOP_DEFAULT_VALUE / 2. - 10.;
pub static GAME_OVER_PANEL_TOP_END_REVERSED: f32 =
    GAME_OVER_PANEL_TOP_DEFAULT_VALUE - GAME_OVER_PANEL_TOP_END;
