use crate::constants::square::assets::{
    SQUARE_IMAGE_FIRST_DEACTIVATED_PATH, SQUARE_IMAGE_SECOND_DEACTIVATED_PATH,
};

pub const TILE_IMAGE_FIRST_DEACTIVATED_PATH: &str = SQUARE_IMAGE_FIRST_DEACTIVATED_PATH;
pub const TILE_IMAGE_SECOND_DEACTIVATED_PATH: &str = SQUARE_IMAGE_SECOND_DEACTIVATED_PATH;
