use crate::constants::square::assets::{
    SQAURE_IMAGE_FIRST_DEACTIVE_PATH, SQAURE_IMAGE_SECOND_DEACTIVE_PATH,
};

pub const TILE_IMAGE_FIRST_DEACTIVE_PATH: &str = SQAURE_IMAGE_FIRST_DEACTIVE_PATH;
pub const TILE_IMAGE_SECOND_DEACTIVE_PATH: &str = SQAURE_IMAGE_SECOND_DEACTIVE_PATH;
