pub const CAMERA_POSITION_Y_IDLE: f32 = 0.5;
pub const CAMERA_POSITION_Y_GAME_OVER: f32 = 0.65;
pub const CAMERA_ANIMATION_IN_POSITION_SPEED: f32 = 2.0;
pub const CAMERA_ANIMATION_OUT_POSITION_SPEED: f32 = 2.0;
