use bevy::math::Vec3;

pub const FIGURE_SPEED_TO_UPSCALE: f32 = 8.;
pub const FIGURE_UPSCALE_SPEED_INCREMENT_FACTOR_PER_FRAME: f32 = 1.;
pub const FIGURE_SPEED_TO_UPSCALING_SPAWN: f32 = 5.;
pub const FIGURE_DRAGGING_SCALE: f32 = 1.;
pub const FIGURE_IDEL_SCALE: f32 = 0.6;
pub const FIGURE_IDEL_SCALE_VEC3: Vec3 = Vec3::splat(FIGURE_IDEL_SCALE);
