use bevy::math::Vec3;

pub const FIGURE_SPEED_UPSCALE: f32 = 8.;
pub const FIGURE_UPSCALE_SPEED_INCREMENT_PER_FRAME: f32 = 1.;
pub const FIGURE_SPAWN_UPSCALE_SPEED: f32 = 5.;
pub const FIGURE_DRAGGING_SCALE: f32 = 1.;
pub const FIGURE_IDLE_SCALE: f32 = 0.6;
pub const FIGURE_IDLE_SCALE_VEC3: Vec3 = Vec3::splat(FIGURE_IDLE_SCALE);
